#ifndef KEYMAP_CONFIG_H
#define KEYMAP_CONFIG_H

#define RGBLIGHT_SLEEP
#define RGBLIGHT_SPLIT
#define RGB_DISABLE_TIMEOUT 5000
#define RGB_DISABLE_WHEN_USB_SUSPENDED 1

#endif // !USERSPACE_CONFIG_H
